version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:13.3
    ports:
      - "5432:5432"
    env_file:
      - .env
      
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000"
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    env_file:
      - .env

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3001:3001" 
    stdin_open: true
    tty: true
    depends_on:
      - backend