# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mbonnet <mbonnet@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/07/06 08:59:48 by mbonnet           #+#    #+#              #
#    Updated: 2022/07/06 13:35:14 by mbonnet          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM nginx

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get install zsh -y
COPY default.conf /etc/nginx/conf.d/default.conf
COPY nginx-selfsigned.crt /etc/ssl/certs/nginx-selfsigned.crt
COPY nginx-selfsigned.key /etc/ssl/private/nginx-selfsigned.key
RUN useradd marco

RUN apt-get install uidmap
RUN apt-get install -y dbus-user-session
RUN apt-get install -y docker-ce-rootless-extras
#RUN /usr/bin/dockerd-rootless-setuptool.sh install
#USER marco
CMD ["nginx", "-g", "daemon off;"]
