# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mbonnet <mbonnet@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/07/06 08:59:48 by mbonnet           #+#    #+#              #
#    Updated: 2022/07/06 12:05:47 by mbonnet          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM nginx

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get install zsh -y
COPY default.conf /etc/nginx/conf.d/default.conf
COPY nginx-selfsigned.crt /etc/ssl/certs/nginx-selfsigned.crt
COPY nginx-selfsigned.key /etc/ssl/private/nginx-selfsigned.key

CMD ["nginx", "-g", "daemon off;"]
